misatfinal:	SAT-final.cpp
	g++ -O3 -Wall SAT-final.cpp -o misatfinal

misatconflictiu: SAT-conflictivitat.cpp
	g++ -O3 -Wall SAT-conflictivitat.cpp -o misatconflictiu

misat:	SAT-alumnes.cpp
	g++ -O3 -Wall SAT-alumnes.cpp -o misat

misatoriginal: SAT-original.cpp
	g++ -O3 -Wall SAT-original.cpp -o misatoriginal
	
